spring.application.name=TimelyManagementSystem
spring.datasource.url=jdbc:mysql://localhost:3306/timely_management?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
