CREATE TABLE revoked_access_token(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    token_id VARCHAR(36) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);